version: '3.1'

services:
  nginx:
    image: 'nginx'
    ports:
      - 80:80
    volumes:
      - './services/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './services/nginx/conf.d:/etc/nginx/conf.d'
      - './services/nginx/sites-available:/etc/nginx/sites-available'
      - './services/nginx/sites-enabled:/etc/nginx/sites-enabled'